/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfacegrafica3.view;

import java.sql.Connection;
import interfacegrafica3.model.Fornecedor;
import interfacegrafica3.model.Pessoa;
import interfacegrafica3.model.Uf;
import interfacegrafica3.repository.FornecedorRepository;
import interfacegrafica3.repository.PessoaRepository;
import interfacegrafica3.repository.UfRepository;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Professor
 */
public class JanelaCadastroFornecedor extends javax.swing.JInternalFrame {

    private static JanelaCadastroFornecedor instancia;
    private JanelaPrincipal janelaPrincipal;
    
    private UfRepository ufRepository = new UfRepository();
    
    public JanelaCadastroFornecedor(JanelaPrincipal janelaPrincipal) {
        initComponents();
        this.janelaPrincipal = janelaPrincipal;
        txtId.setText("0");
        carregarUfs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        bntGravar = new javax.swing.JButton();
        btnAvancar = new javax.swing.JButton();
        btnRetroceder = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        bntDeletar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxUF = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtInsEst = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNomeFan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();

        setTitle("Tela de cadastro");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntFechar.setText("Fechar");
        bntFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntFecharActionPerformed(evt);
            }
        });
        getContentPane().add(bntFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 20));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 290, -1));

        jLabel2.setText("Endereco:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 30));
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 290, -1));

        jLabel3.setText("E-mail:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 86, -1, 30));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 290, -1));

        jLabel4.setText("Telefone:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, 30));
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 290, -1));

        bntGravar.setText("Gravar");
        bntGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGravarActionPerformed(evt);
            }
        });
        getContentPane().add(bntGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        btnAvancar.setText("⏩");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        btnRetroceder.setText("⏪");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 19, -1));

        bntDeletar.setText("Excluir");
        bntDeletar.setToolTipText("");
        bntDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(bntDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jLabel5.setText("UF");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 30));

        ComboBoxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboBoxUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 290, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 162, -1, -1));

        jLabel7.setText("CNPJ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 30));
        getContentPane().add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 290, -1));

        jLabel8.setText("Inscrição Estadual");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 20));
        getContentPane().add(txtInsEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 290, -1));

        jLabel9.setText("Nome Fantasia");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 20));
        getContentPane().add(txtNomeFan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 290, -1));

        jLabel10.setText("Categoria");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));
        getContentPane().add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntFecharActionPerformed
        // TODO add your handling code here:
        fecharJanela();
    }//GEN-LAST:event_bntFecharActionPerformed

    private void carregarUfs(){        
        List<Uf> ufs;
        ufs = ufRepository.selecionarTodos(janelaPrincipal.conexaoMySQL.connection);
        
        ComboBoxUF.removeAllItems();
        if (ufs == null || ufs.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma UF encontrada.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (Uf uf : ufs) {
                ComboBoxUF.addItem(uf.getSigla());
            }
        }
    }
    
    
    private void bntGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGravarActionPerformed

        List<Uf> ufs;
        ufs = ufRepository.selecionarTodos(janelaPrincipal.conexaoMySQL.connection);
        Uf ufEncontrada = null;
        
        String siglaSelecionada = (String) ComboBoxUF.getSelectedItem();

        // Verifica se a sigla selecionada não é nula ou vazia
        if (siglaSelecionada != null && !siglaSelecionada.isEmpty()) {
            List<Uf> listaUfsCopia = new ArrayList<>(ufs);

            // Percorre a cópia da lista para encontrar a UF com a sigla correspondente
            for (Uf uf : listaUfsCopia) {
                if (uf.getSigla().equals(siglaSelecionada)) {
                    ufEncontrada = uf;
                    break;
                }
            }
        } 
       
        // Verifica se uma UF foi selecionada
        if (siglaSelecionada == null) {
            JOptionPane.showMessageDialog(
                this,
                "Selecione uma UF válida.",
                "Erro ao cadastrar fornecedor",
                JOptionPane.ERROR_MESSAGE
            );
            return; // Se não selecionar a UF, não prossegue
        }

        int id = Integer.parseInt(txtId.getText());
        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setNome(txtNome.getText());
        fornecedor.setEndereco(txtEndereco.getText());
        fornecedor.setEmail(txtEmail.getText());
        fornecedor.setTelefone(txtTelefone.getText());
        fornecedor.setCnpj(txtCNPJ.getText());
        fornecedor.setInscricaoEstadual(txtInsEst.getText());
        fornecedor.setNomeFantasia(txtNomeFan.getText());
        fornecedor.setCategoria(txtCategoria.getText());
        fornecedor.setUf(ufEncontrada);

        // Instancia o repositório de fornecedor para realizar a operação no banco
        FornecedorRepository fornecedorRepository = new FornecedorRepository();
        boolean retornoBanco = false;

        // Verifica se o fornecedor é novo ou se é uma atualização
        if (id == 0) {
            // Inserir novo fornecedor
            retornoBanco = fornecedorRepository.inserir(
                janelaPrincipal.conexaoMySQL.connection, 
                fornecedor);
        } else {
            // Atualizar fornecedor existente
            fornecedor.setId(id);
            retornoBanco = fornecedorRepository.atualizar(
                janelaPrincipal.conexaoMySQL.connection, 
                fornecedor);
        }

        // Exibe o retorno da operação
        if (retornoBanco) {
            JOptionPane.showMessageDialog(
                this,
                id == 0 ? "Cadastro efetuado com sucesso!" : "Cadastro atualizado com sucesso!",
                "Tela de cadastro",
                JOptionPane.INFORMATION_MESSAGE
            );
            limparJanela();  // Limpar a janela após operação
        } else {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao salvar o fornecedor.",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }       
        
    }//GEN-LAST:event_bntGravarActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed

        limparJanela();
        
        FornecedorRepository fornecedorRepository = new FornecedorRepository();
        Fornecedor fornecedor = fornecedorRepository.selecionar(janelaPrincipal.conexaoMySQL.connection, ">", Integer.parseInt(txtId.getText()));
        
        if(fornecedor != null){
            
            int idUf = fornecedor.getUf().getId();
            
            txtNome.setText(fornecedor.getNome());
            txtEmail.setText(fornecedor.getEmail());
            txtEndereco.setText(fornecedor.getEndereco());
            txtTelefone.setText(fornecedor.getTelefone());
            txtCNPJ.setText(fornecedor.getCnpj());
            txtInsEst.setText(fornecedor.getInscricaoEstadual());
            txtNomeFan.setText(fornecedor.getNomeFantasia());
            txtCategoria.setText(fornecedor.getCategoria());
            txtId.setText(String.valueOf(fornecedor.getId()));
            ComboBoxUF.setSelectedIndex(idUf - 1);
            } else{
                limparJanela();
                txtId.setText("0");
            }
        
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
       
        limparJanela();
        
        FornecedorRepository fornecedorRepository = new FornecedorRepository();
        Fornecedor fornecedor = fornecedorRepository.selecionar(janelaPrincipal.conexaoMySQL.connection, "<", Integer.parseInt(txtId.getText()));
        
        if(fornecedor != null){
            
            int idUf = fornecedor.getUf().getId();
            
            txtNome.setText(fornecedor.getNome());
            txtEmail.setText(fornecedor.getEmail());
            txtEndereco.setText(fornecedor.getEndereco());
            txtTelefone.setText(fornecedor.getTelefone());
            txtCNPJ.setText(fornecedor.getCnpj());
            txtInsEst.setText(fornecedor.getInscricaoEstadual());
            txtNomeFan.setText(fornecedor.getNomeFantasia());
            txtCategoria.setText(fornecedor.getCategoria());
            txtId.setText(String.valueOf(fornecedor.getId()));
            ComboBoxUF.setSelectedIndex(idUf - 1);
            } else{
                limparJanela();
                txtId.setText("0");
            }
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void bntDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDeletarActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(txtId.getText()) > 0){
            int resposta = JOptionPane.showConfirmDialog(
                    this,
                    "Deseja realmente excluir esse registro?",
                    "Excluir?",
                    JOptionPane.YES_NO_OPTION
            );
            if(resposta == JOptionPane.YES_OPTION){
                //excluir registro:
                int id = Integer.parseInt(txtId.getText());
                Fornecedor fornecedor = new Fornecedor();
                fornecedor.setId(id);
                FornecedorRepository fornecedorRepository = new FornecedorRepository();
                boolean retornoBanco = fornecedorRepository.deletar(
                        janelaPrincipal.conexaoMySQL.connection,
                        fornecedor
                );
                if(retornoBanco){
                    limparJanela();
                    txtId.setText("0");
                    JOptionPane.showMessageDialog(
                            this,
                            "Registro excluído com sucesso!",
                            "Tela de cadastro",
                            JOptionPane.INFORMATION_MESSAGE
                    );
                }                
                
            }            
        }
    }//GEN-LAST:event_bntDeletarActionPerformed
    
    private void limparJanela(){
        txtNome.setText("");
        txtEmail.setText("");
        txtEndereco.setText("");
        txtTelefone.setText("");
        txtCNPJ.setText("");
        txtInsEst.setText("");
        txtNomeFan.setText("");
        txtCategoria.setText("");
        ComboBoxUF.setSelectedIndex(0);
        txtNome.requestFocus();
    }
    
    private void fecharJanela(){
        instancia = null;
        dispose();
    }
    
    public static JanelaCadastroFornecedor getInstancia(JanelaPrincipal janelaPrincipal){
        if(instancia == null)
            instancia = new JanelaCadastroFornecedor(janelaPrincipal);
        return instancia;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxUF;
    private javax.swing.JButton bntDeletar;
    private javax.swing.JButton bntFechar;
    private javax.swing.JButton bntGravar;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtInsEst;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeFan;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
